version: '3.8'

services:
    app:
        container_name: ecom-backend-${ENVIRONMENT_NAME}
        build:
            context: .
            args:
                - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
                - BRANCH_NAME=${BRANCH_NAME}
            dockerfile: docker/Dockerfile
        ports:
            - "${PORT}:3310"
        environment:
            - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
            - CHOKIDAR_USEPOLLING=true
        networks:
            - app-network

    nginx:
        container_name: ecom-backend-nginx-${ENVIRONMENT_NAME}
        restart: unless-stopped
        tty: true
        build:
            context: .
            args:
                - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
            dockerfile: docker/nginx.Dockerfile
        ports:
            - "3309:${PORT}"
        volumes:
            - /home/projects/ecom-backend-${ENVIRONMENT_NAME}:/app
        networks:
            - app-network

networks:
    default:
        name: nginx-proxy
        external: true
    app-network:
        driver: bridge
