version: '3.8'

services:
    app:
        container_name: ecom-backend-${ENVIRONMENT_NAME}
        restart: unless-stopped
        ports:
            - "${PORT}:3001"
        build:
            context: .
            args:
                - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
                - BRANCH_NAME=${BRANCH_NAME}
            dockerfile: docker/Dockerfile
        environment:
            - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
            - APP_PORT=${PORT}
            - CHOKIDAR_USEPOLLING=true

networks:
    default:
        name: nginx-proxy
        external: true
