version: '3.8'

services:
    app:
        container_name: ecom-backend-${ENVIRONMENT_NAME}
        build:
            context: .
            args:
                - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
                - BRANCH_NAME=${BRANCH_NAME}
            dockerfile: docker/Dockerfile
        ports:
            - "${PORT}:3000"
        environment:
            - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
            - CHOKIDAR_USEPOLLING=true
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: ecom-nginx-${ENVIRONMENT_NAME}
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /home/username/laravel:/app
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network

networks:
    default:
        name: nginx-proxy
        external: true
    app-network:
        driver: bridge
